before merge with master

diff --git a/test/local/run-checks.in b/test/local/run-checks.in
--- a/test/local/run-checks.in
+++ b/test/local/run-checks.in
@@ -291,7 +291,7 @@ run_failure() {
         base="Global"
         node0=""
         node2=""
-    elif [ $4 = "MPIIO" ]; then
+    elif [ $4 = "MPIIO" -o $4 = "SIONLIB" ]; then
         base="Global"
         node0=""
         node2=""
@@ -306,7 +306,7 @@ run_failure() {
     if [ "$1" = "CORRUPT" ]; then
         if [ "$2" = "CKPT" ]; then
             echo -e "[ \033[1mCorrupting Checkpoint Files...\033[m ]"
-            if [ $4 = "MPIIO" ]; then
+            if [ $4 = "MPIIO" -o $4 = "SIONLIB" ]; then
                 files=$base/$check_id/l$level/*
             else
                 files="$(find $base/$node0/$check_id/l$level | grep Rank | head -n 1) $(find $base/$node2/$check_id/l$level | grep Rank | head -n 1)"
@@ -325,7 +325,7 @@ run_failure() {
     if [ "$1" = "ERASE" ]; then
         if [ "$2" = "CKPT" ]; then
             echo -e "[ \033[1mDeleting Checkpoint Files...\033[m ]"
-            if [ $4 = "MPIIO" ]; then
+            if [ $4 = "MPIIO" -o $4 = "SIONLIB" ]; then
                 files=$base/$check_id/l$level/*
             else
                 files="$(find $base/$node0/$check_id/l$level | grep Rank | head -n 1) $(find $base/$node2/$check_id/l$level | grep Rank | head -n 1)"
@@ -411,6 +411,7 @@ MEM_NAMES=(@MEMORYTYPES@)
 
 if [ ! -z "$CFG_FILE" ]; then
     TESTRECOVERVAR=$(grep -E "^RECOVERVAR" $CFG_FILE)
+    TESTRECOVERNAME=$(grep -E "^RECOVERNAME" $CFG_FILE)
     TESTVPR=$(grep -E "^VPR" $CFG_FILE)
     TESTICP=$(grep -E "^VPR" $CFG_FILE)
     TESTDCPPOSIX=$(grep -E "^DCPPOSIX" $CFG_FILE)
@@ -439,6 +440,31 @@ for io in ${!IO_NAMES[@]}; do
         should_not_fail $?
         if [ $testFailed = 1 ]; then
             echo -e ${IO_NAMES[$io_id]}"(recoverVar): L"$level", head=0, keep="$keep", inline=(1,1,1), should recover, ID: "$check_id >> failed.log
+            testFailed=0
+        fi
+    done
+done    
+fi
+
+#                     #
+# ---- Check Recover Name ---- #
+#                     #
+if [ ! -z $TESTRECOVERNAME ]; then
+for io in ${!IO_NAMES[@]}; do
+    let io_id=io-1
+    get_io ${IO_NAMES[$io_id]}
+    awk -v var=$io_mode '$1 == "ckpt_io" {$3 = var}1' TMPLT > tmp; cp tmp TMPLT
+    keep=0
+    NAME="H0K"$keep"I111"
+    for level in ${LEVEL[*]}; do
+        awk -v var="$keep" '$1 == "keep_last_ckpt" {$3 = var}1' TMPLT > tmp; cp tmp $NAME
+        echo -e "[ \033[1m*** Testing "${IO_NAMES[$io_id]}"(Recover Name): L"$level", head=0, inline=(1,1,1) ... ***\033[m ]"
+        ( set -x; $MPIRUN -n $PROCS ./recoverName/recoverName.exe $NAME 1 $level 1 &>> check.log )
+        check_id=$(awk '$1 == "exec_id" {print $3}' < $NAME)
+        ( cmdpid=$BASHPID; (sleep $TIMEOUT; kill $cmdpid > /dev/null 2>&1 ) & set -x; $MPIRUN -n $PROCS ./recoverName/recoverName.exe $NAME 0 $level $diffSize $MEM &>> check.log )
+        should_not_fail $?
+        if [ $testFailed = 1 ]; then
+            echo -e ${IO_NAMES[$io_id]}"(recoverName): L"$level", head=0, keep="$keep", inline=(1,1,1), should recover, ID: "$check_id >> failed.log
             testFailed=0
         fi
     done
@@ -622,20 +648,35 @@ fi
 # ---- Check KL4 ---- #
 #                     #
 if [ ! -z $TESTKEEPL4 ]; then
-echo -e "[ \033[1m*** Testing KL4: head=0 ***\033[m ]"
+echo -e "[ \033[1m*** Testing KL4: head=0 KEEP = 0***\033[m ]"
 ( set -x; bash checkKL4.sh 0 &>> check.log )
 check_return_val $?
 if [ $testFailed = 1 ]; then
-    echo -e "KL4 check (head=0) failed" >> failed.log
+    echo -e "KL4 check (head=0 && keep last = 0) failed" >> failed.log
     testFailed=0
 fi
-echo -e "[ \033[1m*** Testing KL4: head=1 ***\033[m ]"
+echo -e "[ \033[1m*** Testing KL4: head=1 KEEP = 0 ***\033[m ]"
 ( set -x; bash checkKL4.sh 1 &>> check.log )
 check_return_val $?
 if [ $testFailed = 1 ]; then
-    echo -e "KL4 check (head=1) failed" >> failed.log
+    echo -e "KL4 check (head=1 && keep last = 0) failed" >> failed.log
     testFailed=0
 fi
+echo -e "[ \033[1m*** Testing KL4: head=0 KEEP LAST = 1 ***\033[m ]"
+( set -x; bash checkKL4.sh 2 &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "KL4 check (head=0 && keep last = 0) failed" >> failed.log
+    testFailed=0
+fi
+echo -e "[ \033[1m*** Testing KL4: head=1 KEEP LAST = 1 ***\033[m ]"
+( set -x; bash checkKL4.sh 3 &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "KL4 check (head=0 && keep last = 1) failed" >> failed.log
+    testFailed=0
+fi
+
 fi
 
 if [ ! -z $TESTSTANDARD ]; then
@@ -711,7 +752,7 @@ for MEM in "${!MEM_NAMES[@]}"; do
                               run_failure "CORRUPT" "ENC" "PASS" "LOCAL"
                           fi
                           if [ $level = 4 ]; then
-                              if [ ${IO_NAMES[$io_id]} = "MPIIO" ]; then
+                              if [ ${IO_NAMES[$io_id]} = "MPIIO" -o ${IO_NAMES[$io_id]} = "SIONLIB" ]; then
                                   run_failure "CORRUPT" "CKPT" "FAIL" "MPIIO"
                               else
                                   run_failure "CORRUPT" "CKPT" "FAIL" "GLOBAL"
@@ -735,7 +776,7 @@ for MEM in "${!MEM_NAMES[@]}"; do
                               run_failure "ERASE" "NONCONSECUTIVE_NODE" "PASS" "LOCAL"
                           fi
                           if [ $level = 4 ]; then
-                              if [ ${IO_NAMES[$io_id]} = "MPIIO" ]; then
+                              if [ ${IO_NAMES[$io_id]} = "MPIIO" -o ${IO_NAMES[$io_id]} = "SIONLIB" ]; then
                                   run_failure "ERASE" "CKPT" "FAIL" "MPIIO"
                               else
                                   run_failure "ERASE" "CKPT" "FAIL" "GLOBAL"
@@ -810,7 +851,7 @@ for MEM in "${!MEM_NAMES[@]}"; do
                                       run_failure "CORRUPT" "ENC" "PASS" "LOCAL"
                                   fi
                                   if [ $level = 4 ]; then
-                                      if [ ${IO_NAMES[$io_id]} = "MPIIO" ]; then
+                                      if [ ${IO_NAMES[$io_id]} = "MPIIO" -o ${IO_NAMES[$io_id]} = "SIONLIB" ]; then
                                           run_failure "CORRUPT" "CKPT" "FAIL" "MPIIO"
                                       else
                                           run_failure "CORRUPT" "CKPT" "FAIL" "GLOBAL"
@@ -834,7 +875,7 @@ for MEM in "${!MEM_NAMES[@]}"; do
                                       run_failure "ERASE" "NONCONSECUTIVE_NODE" "PASS" "LOCAL"
                                   fi
                                   if [ $level = 4 ]; then
-                                      if [ ${IO_NAMES[$io_id]} = "MPIIO" ]; then
+                                      if [ ${IO_NAMES[$io_id]} = "MPIIO" -o ${IO_NAMES[$io_id]} = "SIONLIB" ]; then
                                           run_failure "ERASE" "CKPT" "FAIL" "MPIIO"
                                       else
                                           run_failure "ERASE" "CKPT" "FAIL" "GLOBAL"
