cleanup

diff --git a/test/local/run-checks.in b/test/local/run-checks.in
--- a/test/local/run-checks.in
+++ b/test/local/run-checks.in
@@ -312,76 +312,76 @@ INLINE_L4=(0 1)
 KEEP=(0 1)
 IO_NAMES=(@IO_NAMES@)
 
-##                     #
-## ---- Check dCP ---- #
-##                     #
-#echo -e "[ \033[1m*** Testing dCP: head=0 ***\033[m ]"
-#( set -x; bash checkDCP.sh 0 NOICP &>> check.log )
-#check_return_val $?
-#if [ $testFailed = 1 ]; then
-#    echo -e "dCP check (head=0) failed" >> failed.log
-#    testFailed=0
-#fi
-#echo -e "[ \033[1m*** Testing dCP: head=1 ***\033[m ]"
-#( set -x; bash checkDCP.sh 1 NOICP &>> check.log )
-#check_return_val $?
-#if [ $testFailed = 1 ]; then
-#    echo -e "dCP check (head=1) failed" >> failed.log
-#    testFailed=0
-#fi
-#
-##                     #
-## ---- Check iCP ---- #
-##                     #
-#echo -e "[ \033[1m*** Testing iCP: head=0 ***\033[m ]"
-#( set -x; bash checkDCP.sh 0 ICP &>> check.log )
-#check_return_val $?
-#if [ $testFailed = 1 ]; then
-#    echo -e "dCP check (head=0) failed" >> failed.log
-#    testFailed=0
-#fi
-#echo -e "[ \033[1m*** Testing iCP: head=1 ***\033[m ]"
-#( set -x; bash checkDCP.sh 1 ICP &>> check.log )
-#check_return_val $?
-#if [ $testFailed = 1 ]; then
-#    echo -e "dCP check (head=1) failed" >> failed.log
-#    testFailed=0
-#fi
-##                     #
-## ---- Check GIO ---- #
-##                     #
-#echo -e "[ \033[1m*** Testing staging: head=1 ***\033[m ]"
-#( set -x; bash checkGIO.sh 1 &>> check.log )
-#check_return_val $?
-#if [ $testFailed = 1 ]; then
-#    echo -e "GIO check (head=1) failed" >> failed.log
-#    testFailed=0
-#fi
-#echo -e "[ \033[1m*** Testing staging: head=0 ***\033[m ]"
-#( set -x; bash checkGIO.sh 0 &>> check.log )
-#check_return_val $?
-#if [ $testFailed = 1 ]; then
-#    echo -e "GIO check (head=0) failed" >> failed.log
-#    testFailed=0
-#fi
-#
-##                     #
-## ---- Check KL4 ---- #
-##                     #
-#echo -e "[ \033[1m*** Testing KL4: head=0 ***\033[m ]"
-#( set -x; bash checkKL4.sh 0 &>> check.log )
-#check_return_val $?
-#if [ $testFailed = 1 ]; then
-#    echo -e "KL4 check (head=0) failed" >> failed.log
-#    testFailed=0
-#fi
-#echo -e "[ \033[1m*** Testing KL4: head=1 ***\033[m ]"
-#( set -x; bash checkKL4.sh 1 &>> check.log )
-#check_return_val $?
-#if [ $testFailed = 1 ]; then
-#    echo -e "KL4 check (head=1) failed" >> failed.log
-#    testFailed=0
-#fi
+#                     #
+# ---- Check dCP ---- #
+#                     #
+echo -e "[ \033[1m*** Testing dCP: head=0 ***\033[m ]"
+( set -x; bash checkDCP.sh 0 NOICP &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "dCP check (head=0) failed" >> failed.log
+    testFailed=0
+fi
+echo -e "[ \033[1m*** Testing dCP: head=1 ***\033[m ]"
+( set -x; bash checkDCP.sh 1 NOICP &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "dCP check (head=1) failed" >> failed.log
+    testFailed=0
+fi
+
+#                     #
+# ---- Check iCP ---- #
+#                     #
+echo -e "[ \033[1m*** Testing iCP: head=0 ***\033[m ]"
+( set -x; bash checkDCP.sh 0 ICP &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "dCP check (head=0) failed" >> failed.log
+    testFailed=0
+fi
+echo -e "[ \033[1m*** Testing iCP: head=1 ***\033[m ]"
+( set -x; bash checkDCP.sh 1 ICP &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "dCP check (head=1) failed" >> failed.log
+    testFailed=0
+fi
+#                     #
+# ---- Check GIO ---- #
+#                     #
+echo -e "[ \033[1m*** Testing staging: head=1 ***\033[m ]"
+( set -x; bash checkGIO.sh 1 &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "GIO check (head=1) failed" >> failed.log
+    testFailed=0
+fi
+echo -e "[ \033[1m*** Testing staging: head=0 ***\033[m ]"
+( set -x; bash checkGIO.sh 0 &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "GIO check (head=0) failed" >> failed.log
+    testFailed=0
+fi
+
+#                     #
+# ---- Check KL4 ---- #
+#                     #
+echo -e "[ \033[1m*** Testing KL4: head=0 ***\033[m ]"
+( set -x; bash checkKL4.sh 0 &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "KL4 check (head=0) failed" >> failed.log
+    testFailed=0
+fi
+echo -e "[ \033[1m*** Testing KL4: head=1 ***\033[m ]"
+( set -x; bash checkKL4.sh 1 &>> check.log )
+check_return_val $?
+if [ $testFailed = 1 ]; then
+    echo -e "KL4 check (head=1) failed" >> failed.log
+    testFailed=0
+fi
 
 for io in $(seq 1 @IO@); do
     for enable_icp in OFF ON; do
