finish up dCP unit testing

diff --git a/test/local/run-checks.in b/test/local/run-checks.in
--- a/test/local/run-checks.in
+++ b/test/local/run-checks.in
@@ -288,11 +288,18 @@ IO_NAMES=(@IO_NAMES@)
 #                     #
 # ---- Check dCP ---- #
 #                     #
-echo -e "[ \033[1m*** Testing dCP ***\033[m ]"
-( set -x; bash checkDCP.sh &>> check.log )
+echo -e "[ \033[1m*** Testing dCP: head=0 ***\033[m ]"
+( set -x; bash checkDCP.sh 0 &>> check.log )
 dCP_check $?
 if [ $testFailed = 1 ]; then
-    echo -e "dCP check failed!" >> failed.log
+    echo -e "dCP check (head=0) failed" >> failed.log
+    testFailed=0
+fi
+echo -e "[ \033[1m*** Testing dCP: head=1 ***\033[m ]"
+( set -x; bash checkDCP.sh 0 &>> check.log )
+dCP_check $?
+if [ $testFailed = 1 ]; then
+    echo -e "dCP check (head=1) failed" >> failed.log
     testFailed=0
 fi
 
