Integrated and fixed a bug on keepl4 fixture

diff --git a/test/itf/api b/test/itf/api
--- a/test/itf/api
+++ b/test/itf/api
@@ -252,6 +252,18 @@ check_non_zero() {
     fi
 }
 
+check_file_exists() {
+    # Assert that a file exists
+    #
+    # Parameters:
+    # $1: The file path
+
+    if ! ls $1 1> /dev/null 2>&1;
+    then
+        fail "File not found: $1"
+    fi
+}
+
 assert_equals() {
     # Assert if a value is equal to another and finalize test case
     #
@@ -273,6 +285,16 @@ assert_not_equals() {
     # $3: An optional message in case of failure
 
     check_not_equals $1 $2 "$3"
+    pass
+}
+
+assert_file_exists() {
+    # Assert that a file exists
+    #
+    # Parameters:
+    # $1: The file path
+
+    check_file_exists $1
     pass
 }
 
