Removed set -e from the engine and API, this would make the test case fail silently

diff --git a/testing/itf/engine b/testing/itf/engine
--- a/testing/itf/engine
+++ b/testing/itf/engine
@@ -14,14 +14,13 @@ itf_load_fixture() {
     # Parameters:
     # $1: The fixture name without the .fixture extension
 
-    set -e
-
     itf_loaded_fixture="$(basename "$1")"
     itf_fixture_had_errors='false'
     source "$1"
+    if [ $? -ne 0 ]; then
+      fail 'Fixture file not found'
+    fi
     itf_clear_logs
-
-    set +e
 }
 
 itf_unload_fixture() {
@@ -242,8 +241,6 @@ itf_find_fti_objects() {
     # When the object is 'node' returns:
     # - Local node directory for every supplied node
 
-    set -e
-
     if [ ! $1 == 'global' ] && [ -z $level ]; then
         fail '$level variable must be set for ITF to delete checkpoint files'
     fi
@@ -287,8 +284,6 @@ itf_find_fti_objects() {
         fi
     done
     echo "$_files"
-
-    set +e
 }
 
 itf_param_clear() {
